name: hundo_env
channels:
    - bioconda
    - r
    - defaults
    - conda-forge
dependencies:
    - python
    - bbmap
    - biom-format
    - blast
    - clustalo
    - fasttree
    - numpy
    - snakemake
    - vsearch
